[package]
name = "custom_widgets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.17.1"
nannou_egui = { version = "0.4", path = "../nannou_egui" }
